# Generated by Django 6.0.3 on 2026-04-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('passenger', 'Passenger'), ('driver', 'Driver')], default='', max_length=20),
        ),
    ]
